FROM centos:7.5.1804

RUN yum install -y python pip2 python-setuptools

RUN mkdir -p          /code/wss \
 && mkdir -p          /code/ssl
COPY wss/              /code/wss/
COPY ssl/              /code/ssl/
COPY setup.py          /code/
RUN ls -R /code

WORKDIR /code/
RUN python setup.py install
CMD ["python2", "/code/wws/wssclient.py"]