FROM centos:7.5.1804


RUN yum install -y python pip2 python-setuptools
RUN  mkdir -p          /code/wss
COPY wss               /code
COPY setup.py          /code

WORKDIR /code
RUN python setup.py install
CMD ["python2", "wss/wssclient.py"]