FROM centos:7.5.1804

RUN yum install -y python pip2 python-setuptools

RUN  mkdir -p          /code/wss
COPY wss/              /code/wss
COPY setup.py          /code/
RUN ls -R /code

WORKDIR /code/
RUN python setup.py install
CMD ["python2", "/code/wws/wssclient.py"]