FROM centos:7.5.1804


#COPY repo/CentOS-Base.repo /etc/yum.repos.d/
#RUN yum clean all \
# && yum makecache


RUN yum install -y python pip2 python-setuptools
RUN  mkdir -p          /code/wss
COPY wss_server.py     /code
COPY wss               /code
COPY setup.py          /code


WORKDIR /code
RUN python setup.py install
CMD ["python2", "wss_server.py"]