FROM centos:7.5.1804

RUN  mkdir -p          /code/wss
COPY wss_server.py     /code
COPY wss               /code
COPY setup.py          /code

WORKDIR /code
RUN python setup.py install
CMD ["python2", "wss_server.py"]